{% set name = "activesupport" %}
{% set version = "5.0.0.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 496670668a91e9f492830c105a0002ca921138525d5b017372dcfae811c9f2ed

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-i18n >=0.7,<1
    - rb-minitest >=5.1,<6
    - rb-thread_safe >=0.3.4,<1
    - rb-tzinfo >=1.1,<2

test:
  commands:
    - gem list -i {{ name }} -v {{ version }}
    - ruby -r active_support -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/MIT-LICENSE
  summary: A toolkit of support libraries and Ruby core extensions extracted from the Rails framework.

  doc_url: https://www.rubydoc.info/gems/{{ name }}

extra:
  recipe-maintainers:
    - sodre
