travis:
  secure:
    BINSTAR_TOKEN: IO1Ecg8mKocwFqGJ8sZTGFbxY8ZCU/Iv5fgq+uZ9iSzSsADIv1NQoCScT5oYtjAaoN9NXe7QPlnS4TtLgx/MfIJWS1SUTqePd3y0hrJzfZewqEzYi7Vx0jhJEknjzJn1Y2SgWJvfqMnwew9S7aXsgKNzoT0BJmowSQ61JJ6fybDSyjOzEufJwO0l7fWsN0I2DKTTDAgnvpOh2MmVz9nPyvBoib53K3n2cS7O0l1dsd+dKHp+PLNzJ/3M2rFzwGpgVC0DxmEV3LPe7zUGhGk1NHKVPGCFmkoBTIIMFKIWNvodsU2tgwjIxhAfE/EcLF6TrxXf/N9kV7pq3mCEed3sj+6/VHR03e1haZA1FbmoZa8EBc1OhEbwXI/ijJZ0Jgn+bsTIpW++z47n/0eqaHbqF75JZuX55ciE0MVh+ED73uwM7V5vh5UJKFGq+TCfrCAXkyw5HwSKvunaN2oW9TOpUq4M0ag38oxJP40S8MkiBAagXF4drMnyCTNWCvtq3I1kfITAkwlvL38AK8wwZZ0uz+ECvIZYzQ/UmgxdiygcHC+Nh1dt6GzTaz8YEk0U2cW0jtPor23VjxmUdkLwAToFzj3snYT5sB5o+84ZncQvBHjVx3JRKsrbYWIgCLs7SYbro4ZGNEFuloL8RjoCZhX3HO9+WbQd+wAfOpucAOSHcwA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
